[_]
schema-version = "0.2"

[com.salesforce]
schema-version = "0.1"
id = "youtubestats"
description = "This function receives a playlist id, retrieves its videos, and store each video statistics in Salesforce"
type = "function"
